In [3]:
import numpy as np
a = np.array([1,2,3],dtype='int32') #1-D array data type int32
print(a)

[1 2 3]


In [4]:
b= np.array([[1,2,3,4,5],[6,7,8,9,10]]) #2-D array
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
#Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [6]:
#Shape
print(a.shape)  #1 row and 3 columns
print(b.shape)  #2 rows and 5 columns

(3,)
(2, 5)


In [7]:
#Data type
print(a.dtype)  #data type of elements in the array
print(b.dtype)  

int32
int64


In [8]:
#Get size
print(a.itemsize) #size of each element in the array
print(b.itemsize)

4
8


In [9]:
#Get total size
print(a.size) #total number of elements in the array
print(b.size)

3
10


In [10]:
#Accesing/Changing specific elements, rows, columns, etc
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
#Get a specific element [r,c]
print(a[1,5]) #13
print(a[1,-2]) #13
print(a[1,6])  #14
print(a[1,-1]) #14

13
13
14
14


In [12]:
#Get a specific row
print(a[0,:]) #1st row
print(a[1,:]) #2nd row

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [13]:
#Get a specific column
print(a[:,0]) #1st column
print(a[:,1]) #2nd column
print(a[:,2]) #3rd column

[1 8]
[2 9]
[ 3 10]


In [14]:
#Getting a little more fancy [startindex:endindex:stepsize]
print(a[0,1:6:2]) #start from index 1 and go upto index 6 with step size 2
print(a[0,1:-3:2]) #start from index 1 and go upto index -3 with step size 2
print(a[1,2:6:3]) #start from index 2 and go upto index 6 with step size 3
print(a[1,1:6:3]) #start from index 1 and go upto index 6 with step size 3

[2 4 6]
[2 4]
[10 13]
[ 9 12]


In [15]:
#Changing elements
a[1,4] = 20 #change element at 1st row and 4th column to 20
print(a)
a[:,4] = 5  #change all elements in 5th column to 5
print(a)
a[1,:] = 10 #change all elements in 2nd row to 10
print(a)
a[2:4,2:5] = 0 #change elements from 2nd row to 4th row and 2nd column to 5th column to 0
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 20 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11  5 13 14]]
[[ 1  2  3  4  5  6  7]
 [10 10 10 10 10 10 10]]
[[ 1  2  3  4  5  6  7]
 [10 10 10 10 10 10 10]]


3-d array example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])#3-D array
print(b)
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])#3-D array
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
#Get specific element (work outside in)
print(b[0,1,1]) #4
print(b[1,0,1]) #6
print(c[0,0,0]) #1

4
6
1


In [18]:
#replace
b[:,1,:] = [[9,9],[8,8]] #replace 2nd row of all 2-D arrays with [9,9] and [8,8]
print(b)
print("\n")
b[:,0,:] = [[9,9],[8,8]] #replace 1st row of all 2-D arrays with [9,9] and [8,8]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


[[[9 9]
  [9 9]]

 [[8 8]
  [8 8]]]


Initializing different types of arrays

In [19]:
#All 0s matrix
print(np.zeros((2,3))) #2 rows and 3 columns

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
#All 1s matrix
print(np.ones((4,2,2),dtype='int32')) #4 2x2 matrix
print("\n")
print(np.ones((2,5,5),dtype='int32')) #5 5x5 matrix

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [21]:
#Any other number
print(np.full((2,2,2),99,dtype='float32')) #2x2 matrix with all 99
print("\n")
print(np.full((4,4,4),100,dtype='int32')) #4x4 matrix with all 100

[[[99. 99.]
  [99. 99.]]

 [[99. 99.]
  [99. 99.]]]


[[[100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]]

 [[100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]]

 [[100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]]

 [[100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]]]


In [22]:
#Any other number (full_like)
print(np.full_like(a,4)) #2x7 matrix with all 4
print("\n")
print(np.full_like(a,5)) #2x7 matrix with all 5

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]]


In [23]:
#Random decimal numbers
print(np.random.rand(4,2)) #4x2 matrix with random decimal
print(np.random.random_sample(a.shape)) #2x7 matrix with random decimal
print("\n")
matrix = np.random.rand(4,4).astype(np.float64) #4x4 matrix with random decimal
print(matrix)
print("\n")
matrix1 = np.random.uniform(0,10,(4,4)).astype(np.int64) #4x4 matrix with random decimal between 0 and 10
print(matrix1)

[[0.76004753 0.62064279]
 [0.21518081 0.8664196 ]
 [0.41431432 0.98316039]
 [0.49827706 0.47193343]]
[[0.98870452 0.14629417 0.82609445 0.75362141 0.25572065 0.4315058
  0.02540576]
 [0.07501357 0.58579136 0.52621591 0.25435729 0.15701693 0.55793517
  0.53956181]]


[[0.9832565  0.1928076  0.96493551 0.29395467]
 [0.60140844 0.28106535 0.85282465 0.9720594 ]
 [0.94224437 0.19702071 0.64368812 0.56815856]
 [0.96639806 0.81400075 0.20963613 0.35570006]]


[[9 2 4 9]
 [4 4 6 2]
 [5 3 4 0]
 [7 4 9 2]]


In [24]:
#Random integer values
print(np.random.randint(5,7,size=(3,3))) #3x3 matrix with random integer values from 0 to 6
print(np.random.randint(-5,7,size=(3,3))) #3x3 matrix with random integer values from -5 to 6

[[5 6 5]
 [5 5 5]
 [6 6 5]]
[[-1 -2  2]
 [-5 -1 -3]
 [-2 -5  5]]


In [25]:
#indentity matrix
print(np.identity(3)) #3x3 matrix with 1s in diagonal
print("\n")
print(np.identity(4,dtype="float32")) #4x4 matrix with 1s in diagonal

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
#Repeat an array
arr = np.array([[1,2,3]])
print(arr)
"""In NumPy, the term axis refers to the dimensions of an array.
For a 2-D array, axis=0 refers to the rows and axis=1 refers to the columns."""
"""axis=0 refers to the vertical direction (down the rows).
axis=1 refers to the horizontal direction (across the columns)."""

print(arr.size) #3
r1 = np.repeat(arr,3,axis=0) #repeat array 3 times along row
print(r1)
print("\n")
r2 = np.repeat(arr,3,axis=0) #repeat array 3 times along column
print(r2)
print("\n")
r3 = np.repeat(arr,3,axis=1) #repeat array 3 times along row
print(r3)

[[1 2 3]]
3
[[1 2 3]
 [1 2 3]
 [1 2 3]]


[[1 2 3]
 [1 2 3]
 [1 2 3]]


[[1 1 1 2 2 2 3 3 3]]


In [27]:
output = np.ones((5,5))
print(output)
print("\n")
z = np.zeros((3,3))
z[1,1] = 9
print(z)
print("\n")
output[1:-1,1:-1] = z #from 1st row to 4th row and 1st column to 4th column replace with z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#Be careful while copying arrays

In [28]:
a= np.array([1,2,3])
b = a.copy()
print(b)

[1 2 3]


Mathematics:

In [29]:
#Adding into array
a= np.array([1,2,3])
print(a+2)

[3 4 5]


In [30]:
#Subtracting into array
print(a-2)

[-1  0  1]


In [31]:
#Multiplying into array
print(a*2)

[2 4 6]


In [32]:
#Dividing into array
print(a/2)

[0.5 1.  1.5]


In [33]:
#Adding two arrays
b= np.array([1,0,1])
print(a+b)

[2 2 4]


In [34]:
#Square of array
print(a**2)

[1 4 9]


In [35]:
#Take the sin
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


In [36]:
#Take the cos
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925 ]


Linear Algebra

In [37]:
a = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]))  #1-D array
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [38]:
a = np.ones((2,3))
print(a)
b= np.full((3,2),2)
print(b)

#Matrix multiplication
print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [39]:
#Find the determinant
c = np.identity(3)
print(np.linalg.det(c)) #determinant of identity matrix using linear algebra

1.0


In [40]:
print(np.linalg.diagonal(c)) #diagonal of identity matrix using linear algebra

"""Many more functions are available in numpy library for linear algebra"""

[1. 1. 1.]


'Many more functions are available in numpy library for linear algebra'

Statistics in numpy

In [41]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [42]:
np.min(stats) #minimum value in the array

np.int64(1)

In [43]:
np.max(stats) #maximum value in the array

np.int64(6)

Reorganizing arrays

In [44]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [45]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2,v1,v2])) #vertically stack v1 and v2


[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [46]:
#Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(np.hstack((h1,h2))) #horizontally stack h1 and h2
print("\n")


[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]




In [47]:
raw = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(raw) #3-D array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Practice

In [48]:
print(raw[0,:,:])
print(raw[1,0,1])
print(raw[0,0,0])

[[1 2 3]
 [4 5 6]]
8
1


In [49]:
raw1 = np.ones((2,2),dtype='int32')
print(raw1)
print(raw1.itemsize)

[[1 1]
 [1 1]]
4


Data_Handling

In [50]:
with open('Piyush.txt','w') as f:
    f.write("2303\n1033\n1533\n0114")   #write to file

raw2 = np.genfromtxt('piyush.txt',delimiter=',',dtype='int32')  #read from file
raw2.resize((2,2))
print(raw2)

[[2303 1033]
 [1533  114]]


Boolean Masking and Advanced Indexing

In [51]:
raw2>5 #returns boolean values

array([[ True,  True],
       [ True,  True]])

In [52]:
raw2[raw2>5] #returns values greater than 5

array([2303, 1033, 1533,  114], dtype=int32)

In [53]:
#You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] #returns 2nd, 3rd and 9th element

array([2, 3, 9])

axis 0 runs vertically downwards across rows, and axis 1 runs horizontally across columns.

In [54]:
np.any(raw2>5,axis=0) #returns True if any element is greater than 5 in column
np.all(raw2>5,axis=0) #returns True if all elements are greater than 5 in column

array([ True,  True])

In [55]:
a = np.array(range(1,31),dtype='int32')
a.resize((6,5))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [56]:
print(a[2:4,0:2]) #returns 3rd and 4th row and 1st and 2nd column
print(a[2:-1,0:3]) #returns 3rd and 4th row and 1st and 2nd column

[[11 12]
 [16 17]]
[[11 12 13]
 [16 17 18]
 [21 22 23]]


In [57]:
print(a[[0,1,2,3],[1,2,3,4]]) #returns 1st element of 1st row, 2nd element of 2nd row, 3rd element of 3rd row and 4th element of 4th row

[ 2  8 14 20]


In [58]:
print(a[[0,4,5],3:]) #returns 4th and 5th column of 1st, 5th and 6th row

[[ 4  5]
 [24 25]
 [29 30]]


In [59]:
import numpy as np

# Load the data from the file
file = np.genfromtxt('data.txt', delimiter=',', dtype='int64')

# Print the loaded data
print("Loaded data:\n")
print(file)

# Check the shape of the loaded data
print("\nOriginal shape:", file.shape)

# Ensure the total number of elements matches the new shape
if file.size == 3 * 22:
    file = file.reshape(11, 6)
    print("Reshaped data:")
    print(file)
else:
    print(f"Cannot reshape array of size {file.size} into shape (3, 11)")

Loaded data:

[[1 3 3 4 5 6 7 8 5 7 6 4 3 3 4 5 6 7 1 4 6 7]
 [5 8 7 6 7 0 8 2 4 4 6 4 3 9 4 5 6 7 0 5 8 2]
 [6 4 9 3 2 3 1 5 1 7 6 4 3 3 4 5 6 7 3 2 1 3]]

Original shape: (3, 22)
Reshaped data:
[[1 3 3 4 5 6]
 [7 8 5 7 6 4]
 [3 3 4 5 6 7]
 [1 4 6 7 5 8]
 [7 6 7 0 8 2]
 [4 4 6 4 3 9]
 [4 5 6 7 0 5]
 [8 2 6 4 9 3]
 [2 3 1 5 1 7]
 [6 4 3 3 4 5]
 [6 7 3 2 1 3]]


End here...